title:      Beaver Docs

# Build settings
markdown: kramdown
highlighter: none
include:
  - _post

collections:
  docs:
    output: true
    permalink: /:path/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji


paginate: 4
paginate_path: "/page:num/"
